services:
  txt-outlier-backend:
    build: .
    container_name: outlier-backend-deno-container
    image: outlier-backend-deno-image
    ports:
      - "8000:8000"
    volumes:
      - ./backend/logs:/app/backend/logs
      - ./.env:/app/.env:ro
    env_file:
      - .env
    restart: unless-stopped
