services:
  txt-outlier-backend:
    build: .
    container_name: outlier-backend-deno-container
    image: outlier-backend-deno-image
    ports:
      - "443:443"
    volumes:
      - ./backend/logs:/app/backend/logs
    restart: always
