// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $api_drizzle from "./routes/api/drizzle.ts";
import * as $api_joke from "./routes/api/joke.ts";

import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/api/drizzle.ts": $api_drizzle,
    "./routes/api/joke.ts": $api_joke,
  },
  islands: {},
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
