const MISSIVE_API_RATE_LIMIT = 1000
const FIRST_MESSAGES_QUEUE = 'broadcast_first_messages'
const SECOND_MESSAGES_QUEUE_NAME = 'broadcast_second_messages'

const CAMPAIGN_MESSAGES_QUEUE_NAME = 'campaign_messages'
const CAMPAIGN_SECOND_MESSAGES_QUEUE_NAME = 'campaign_second_messages'

export { FIRST_MESSAGES_QUEUE, MISSIVE_API_RATE_LIMIT, SECOND_MESSAGES_QUEUE_NAME, CAMPAIGN_MESSAGES_QUEUE_NAME, CAMPAIGN_SECOND_MESSAGES_QUEUE_NAME }
