version: 2.1

orbs:
  aws-cli: circleci/aws-cli@4.1.3

jobs:
  build-and-test:
    machine:
      image: ubuntu-2204:current # more specific than 'default'
    environment:
      DENO_DIR: ~/.deno # cache Deno dependencies
    steps:
      - checkout

      # Install and setup Deno
      - restore_cache:
          keys:
            - deno-cache-{{ checksum "deno.lock" }} # if you have deno.lock
      - run:
          name: Install Deno
          command: |
            curl -fsSL https://deno.land/x/install@v0.1.9/install.sh | sh
            echo 'export DENO_INSTALL="/home/circleci/.deno"' >> $BASH_ENV
            echo 'export PATH="$DENO_INSTALL/bin:$PATH"' >> $BASH_ENV
      - run:
          name: Upgrade Deno
          command: deno upgrade --version 1.41.3
      - save_cache:
          key: deno-cache-{{ checksum "deno.lock" }}
          paths:
            - ~/.deno

      # Code quality checks
      - run:
          name: Code formatting check
          command: deno task fmt --check
      - run:
          name: Lint check
          command: deno task lint

      # Setup and run tests
      - run:
          name: Install Node.js
          command: |
            curl -fsSL https://deb.nodesource.com/setup_21.x | sudo -E bash -
            sudo apt-get install -y nodejs
      - run:
          name: Setup test environment
          command: deno task test:setup
          background: true # Run in background since it's a server
      - run:
          name: Wait for test setup
          command: sleep 10 # Give test:setup time to start
      - run:
          name: Run tests with coverage
          command: deno task test:coverage
      - run:
          name: Generate coverage report
          command: deno coverage --include="^file:" --exclude="/tests/" supabase/functions/tests/cov_profile

      # Cleanup
      - run:
          name: Cleanup test environment
          command: cd supabase && npx supabase stop
          when: always # Run even if tests fail

workflows:
  test_and_deploy:
    jobs:
      - build-and-test
