version: 2.1

orbs:
  aws-cli: circleci/aws-cli@3.1.4

jobs:
  build-and-test:
    machine:
      image: default
    steps:
      - checkout
      - run: curl -fsSL https://deno.land/install.sh | sh
      - run:
          name: Run lint
          command: /home/circleci/.deno/bin/deno task lint
      - run:
          name: Run fmt
          command: /home/circleci/.deno/bin/deno task fmt --check

      - run: curl -fsSL https://deb.nodesource.com/setup_21.x | sudo -E bash - && sudo apt-get install -y nodejs
      - run:
          name: Setup for test
          command: |
            cd backend/tests
            npx supabase start -x gotrue,realtime,storage-api,imgproxy,inbucket,postgrest,pgadmin-schema-diff,migra,postgres-meta,studio,edge-runtime,logflare,vector, pgbouncer
      - run:
          name: Run the tests
          command: /home/circleci/.deno/bin/deno task test:coverage
      - run:
          name: Coverage
          command: /home/circleci/.deno/bin/deno coverage cov_profile --exclude=tests
      - run:
          name: Clean up after test
          command: |
            cd backend/tests
            npx supabase stop

  deploy-production:
    executor: aws-cli/default
    steps:
      - add_ssh_keys:
          fingerprints:
            - "SHA256:nellmY2hJL/tZt3X0j9w3qftzo2kQeb18M4+hhzTAXw"
      - run:
          command: sleep 1m
          name: Waiting of SSH Server to start at New EC2 Instance
      - run:
          command: ssh $SSH_USER@$SSH_HOST "sh deploy.sh"
          name: Cloning the project

workflows:
  test_and_deploy:
    jobs:
      - build-and-test
      - deploy-production:
          requires:
            - build-and-test
          filters:
            branches:
              only:
                - chores/setup-automatic-deploy-ec2
