version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2204:2022.04.2
    steps:
      - checkout
      - run: curl -fsSL https://deno.land/install.sh | sh
      - run:
          name: Run lint
          command: |
            cd supabase/functions
            /home/circleci/.deno/bin/deno task lint
      - run:
          name: Run fmt
          command: |
            cd supabase/functions
            /home/circleci/.deno/bin/deno task fmt --check

      - run: curl -fsSL https://deb.nodesource.com/setup_21.x | sudo -E bash - && sudo apt-get install -y nodejs
      - run: npx supabase start -x gotrue,realtime,storage-api,imgproxy,inbucket,postgrest,pgadmin-schema-diff,migra,postgres-meta,studio,edge-runtime,logflare,vector, pgbouncer
      - run:
          name: Run the tests
          command: TZ=UTC /home/circleci/.deno/bin/deno test --no-check --allow-all --env=supabase/functions/backend/tests/.env.test --import-map=supabase/functions/backend/tests/import_map.json --coverage=cov_profile --quiet
      - run:
          name: Coverage
          command: /home/circleci/.deno/bin/deno coverage cov_profile --exclude=tests
