version: 2.1

jobs:
  test:
    machine:
      image: default
    steps:
      - checkout
      - run: curl -fsSL https://deno.land/x/install@v0.1.9/install.sh?source | sh
      - run: /home/circleci/.deno/bin/deno upgrade --version 1.41.3
      - run:
          name: Run lint
          command: /home/circleci/.deno/bin/deno task lint
      - run:
          name: Run fmt
          command: /home/circleci/.deno/bin/deno task fmt --check

      - run: curl -fsSL https://deb.nodesource.com/setup_21.x | sudo -E bash - && sudo apt-get install -y nodejs
      - run:
          name: Setup Supabase
          command: npx supabase start
      - run:
          name: Start Functions Server
          command: npx supabase functions serve --env-file supabase/functions/tests/.env.edge_testing
          background: true
      - run:
          name: Wait for services
          command: sleep 30
      - run:
          name: Run tests with coverage
          command: /home/circleci/.deno/bin/deno task test:coverage
      - run:
          name: Run DB tests
          command: /home/circleci/.deno/bin/deno task test:db
      - run:
          name: Generate coverage report
          command: /home/circleci/.deno/bin/deno task coverage
      - run:
          name: Clean up after test
          command: npx supabase stop
          when: always

workflows:
  test:
    jobs:
      - test
