version: 2.1

jobs:
  deploy:
    machine:
      image: ubuntu-2204:2022.04.2

    steps:
      - checkout
      - run:
          name: "Install node"
          command: |
            curl -fsSL https://deb.nodesource.com/setup_21.x | sudo -E bash - && sudo apt-get install -y nodejs
      - run:
          name: "Install Supabase CLI"
          command: npm install supabase --save-dev
      - run:
          name: "Supabase login"
          command: npx supabase login --token $SUPABASE_ACCESS_TOKEN
      - run:
          name: "Deploy Function"
          command: npx supabase functions deploy express --project-ref $SUPABASE_PROJECT_ID

workflows:
  version: 2
  bundle-and-deploy:
    jobs:
      - deploy
#          filters:
#            branches:
#              only:
#                - main
