version: 2.1

jobs:
  build:
    machine:
      image: default
    steps:
      - checkout
      - run: curl -fsSL https://deno.land/install.sh | sh
      - run:
          name: Run lint
          command: /home/circleci/.deno/bin/deno task lint
      - run:
          name: Run fmt
          command: /home/circleci/.deno/bin/deno task fmt --check

      - run: curl -fsSL https://deb.nodesource.com/setup_21.x | sudo -E bash - && sudo apt-get install -y nodejs
      - run:
          name: Setup for test
          command: |
            cd backend/tests
            npx supabase start -x gotrue,realtime,storage-api,imgproxy,inbucket,postgrest,pgadmin-schema-diff,migra,postgres-meta,studio,edge-runtime,logflare,vector, pgbouncer
      - run:
          name: Run the tests
          command: /home/circleci/.deno/bin/deno task test:coverage
      - run:
          name: Coverage
          command: /home/circleci/.deno/bin/deno coverage cov_profile --exclude=tests
      - run:
          name: Clean up after test
          command: |
            cd backend/tests
            npx supabase stop


